name: Doc to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout rep
        uses: actions/checkout@v4

      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: dep i
        run: npm install

      - name: build
        run: npm run docs:build

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Doc to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4