deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: docs
    url: ${{ steps.deployment.outputs.page_url }}

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create redirect index.html
      run: echo '<meta http-equiv="refresh" content="0; url=https://deus-soft.com/">' > docs/.vitepress/dist/index.html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
